server:
  port: 8081

spring:
  application:
    name: ms-authuser
  datasource:
    url: jdbc:postgresql://hotel_db:${DB_PORT}/${AUTHUSER_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
    expiration-seconds: ${SECURITY_JWT_EXPIRATION_SECONDS}

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    db:
      enabled: true
 