server:
  port: 8081

spring:
  application:
    name: ms-authuser
  datasource:
    url: jdbc:postgresql://hotel_db:${DB_PORT}/${AUTHUSER_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null # Omite campos nulos no JSON de resposta

security:
  jwt:
    # Substitua por um valor forte em produção (idealmente Base64) e configure via variável de ambiente SECURITY_JWT_SECRET
    secret: ${SECURITY_JWT_SECRET:change-me-please-change-me-please-change-me-please!}
    # Validade do token em segundos (ex.: 3600 = 1h). Pode ser alterado via SECURITY_JWT_EXPIRATION_SECONDS
    expiration-seconds: ${SECURITY_JWT_EXPIRATION_SECONDS:3600}

 

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    db:
      enabled: true
 