server:
  port: 8080

spring:
  application:
    name: ms-apigateway

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddRequestHeader=X-Request-Source, ms-apigateway
          routes:
            - id: ms-authuser
              uri: http://ms-authuser:8081
              predicates:
                - Path=/auth/**
                - Path=/usuario/**

            - id: ms-propriedade
              uri: http://ms-propriedade:8082
              predicates:
                - Path=/propriedades/**

            - id: ms-reserva
              uri: http://ms-reserva:8083
              predicates:
                - Path=/reservas/**

            - id: ms-notificacao
              uri: http://ms-notificacao:8084
              predicates:
                - Path=/notificacoes/**
              filters:
                # Filtro para proteger o MS-Notificacao de acesso externo
                - name: RewritePath
                  args:
                    regexp: /notificacoes/(?<segment>.*)
                    replacement: /${segment}

          httpclient:
            connect-timeout: 5000
            response-timeout: 10s

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:change-me-please-change-me-please-change-me-please!}
    expiration-seconds: ${SECURITY_JWT_EXPIRATION_SECONDS:3600}