server:
  port: 8083

spring:
  application:
    name: ms-reserva
  datasource:
    url: jdbc:postgresql://hotel_db:${DB_PORT}/${RESERVA_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null

  # Configuração do RabbitMQ
  rabbitmq:
    exchange:
      reserva: reserva-exchange
    host: rabbitmq

# Configurações de Resiliência (Resilience4j)
resilience4j:
  circuitbreaker:
    instances:
      # Circuit Breaker para chamadas críticas
      authServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpen-enabled:  true
      propriedadeServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpen-enabled:  true

app:
  service:
    authuser:
      url: http://ms-authuser:8081/api/authuser

    propriedade:
        url: http://ms-propriedade:8082/api/propriedade