server:
  port: 8082

spring:
  application:
    name: ms-reserva
  datasource:
    url: jdbc:postgresql://hotel_db:${DB_PORT}/${RESERVA_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null # Omite campos nulos no JSON de resposta