name: CI Build & Test (Monorepo)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci_code_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Maven Clean Install and Verify
        run: mvn -B clean verify -DskipTests=true

#       4. (Opcional - Adicione aqui o passo de build do Docker após o 'verify'
#           Se o 'verify' falhar, os passos seguintes não são executados)
      - name: Build Docker Images (Se aplicável)
        run: docker compose build